version: '3.8'

services:
  dbt-pipeline:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=test_db
      - DB_SCHEMA=public
      - DB_PORT=5432
    depends_on:
      - postgres
    volumes:
      - ./target:/app/target
      - ./logs:/app/logs
    networks:
      - dbt-network

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dbt-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - dbt-network

volumes:
  postgres_data:

networks:
  dbt-network:
    driver: bridge
